

min_likes: 30
max_likes: 100
min_to_follow: 10
max_to_follow: 20
max_followers: 10000
min_fallowers: 50
min_following: 50


likes:
  - sunrise
  - sunset
  - drone
  - droneshot
  - dronephotography
  - rigi
  - hallwilersee
  - sempach
  - standuppaddle
  - mountainbike
  - switzerland
  - sonnenaufgang
  - sonnenuntergang
  - drohne
  - see
  - aargau
  - sempachersee
  - water
  - calm
  - relax
  - luzern
  - bern
  - aarau
  - wandern
  - berge
  - droneoftheday
  - nature
  - landscape
  - natur
  - wanderlust
  - lakelife

dont_like:
  - sex
  - nude
  - porn
  - pussy
  - fuck

friends:
 - vireaksoeur
 - amytolja


photo_comments:
  - Nice shot! @{}
  - Love it! @{}
  - Looks awesome @{}
  - Wow! @{}
  - Cool! @{}
  

