min_likes: 50
max_likes: 200
min_to_follow: 1
max_to_follow: 5
max_followers: 500
min_fallowers: 5
min_following: 50
likes_sample: 20
user_interacts: 5

locations:
  - '217254267'
  - '252833442'
  - '5323963'
  - '238158830'
  - '761560033'
  - '452896474757280'
  - '282212720'
  - '249446284'
  - '845416138'

likes:
  - sunrise
  - sunset
  - sonnenaufgang
  - sonnenuntergang
  - droneoftheday
  - drone
  - switzerland
  - mountainbike

random_likes:
  - sunrise
  - sunset
  - drone
  - droneshot
  - dronephotography
  - rigi
  - gislifluh
  - hallwilersee
  - sempach
  - goldenhour
  - standuppaddle
  - mountainbike
  - switzerland
  - sonnenaufgang
  - sonnenuntergang
  - drohne
  - see
  - aargau
  - sempachersee
  - water
  - calm
  - relax
  - luzern
  - bern
  - aarau
  - wandern
  - berge
  - droneoftheday
  - nature
  - landscape
  - natur
  - nature
  - wanderlust
  - lakelife
  - sky
  - relax
  - photography
  - enduro
  - biketour
  - hike
  - hiking
  - biking
  - sonne
  - summer
  - sun
  - summertime

dont_like:
  - sex
  - nude
  - porn
  - pussy
  - fuck

friends:
  - vireaksoeur
  - amytolja

photo_comments:
  - 'Nice shot! @{}'
  - 'Love it! @{}'
  - 'Looks awesome @{}'
  - 'Wow! :fire: @{}'
  - 'Cool! :fire: @{}'
  - 'Wow! @{}'
  - 'Cool! @{}'
  - ':fire: :fire: :fire: @{}'

pods:
  - drone
  - mountainbike
  - standuppaddle
  - hike
  - nature
  - sunrise
