min_likes: 30
max_likes: 100
min_to_follow: 10
max_to_follow: 20
max_followers: 10000
min_fallowers: 50
min_following: 50
likes_sample: 10

locations:
  - 217254267
  - 252833442
  - 5323963
  - 238158830
  - 761560033
  - 452896474757280
  - 282212720
  - 249446284
  - 845416138

likes:
  - sunrise
  - sunset
  - droneoftheday

random_likes:
  - sunrise
  - sunset
  - drone
  - droneshot
  - dronephotography
  - rigi
  - hallwilersee
  - sempach
  - standuppaddle
  - mountainbike
  - switzerland
  - sonnenaufgang
  - sonnenuntergang
  - drohne
  - see
  - aargau
  - sempachersee
  - water
  - calm
  - relax
  - luzern
  - bern
  - aarau
  - wandern
  - berge
  - droneoftheday
  - nature
  - landscape
  - natur
  - wanderlust
  - lakelife
  - sky
  - relax
  - photography
  - enduro
  - biketour
  - hike
  - hiking
  - biking
  - sonne
  - summer
  - sun
  - summertime

dont_like:
  - sex
  - nude
  - porn
  - pussy
  - fuck

friends:
  - vireaksoeur
  - amytolja

photo_comments:
  - Nice shot! @{}
  - Love it! @{}
  - Looks awesome @{}
  - Wow! @{}
  - Cool! @{}
