
likes:
  - sunrise
  - sunset
  - drone
  - droneshot
  - dronephotography
  - rigi
  - hallwilersee
  - sempach
  - standuppaddle
  - mountainbike
  - switzerland
  - sonnenaufgang
  - sonnenuntergang
  - drohne
  - see
  - aargau
  - sempachersee
  - water
  - calm
  - relax
  - luzern
  - bern
  - aarau
  - wandern
  - berge
  - droneoftheday
  - nature
  - landscape
  - natur
  - wanderlust
  - lakelife

  dont_like:
    - sex
    - nude
    - porn
    - pussy
    - girl
    - girls
    - fuck
  
  friends:
   - amytolja
   - vireaksoeur